const awsAccessKey = "AKIAUGZXRMXLVDILPDMP";
const awsSecretKey = "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";


// export AWS_ACCESS_KEY_ID="AKIAUGZXRMXLVDILPDMP"
// export AWS_SECRET_ACCESS_KEY="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"